### ISSUE TITLE
部署到vercel后如何设置为azure环境

### ISSUE THREAD

**Issue by jokerleon** [blrchen/chatgpt-lite#17]
我点击一键部署后，只配置了azure的环境变量，但是请求不到返回
请问还需要设置什么么？

**Comment by blrchen** [comment]
我刚按照首页的文档步骤测试了一下，结果能够成功运行。你可以参考下面的截图，看看是否有什么不同。

<img width="924" alt="image" src="https://user-images.githubusercontent.com/1607381/234209124-f4d76032-97bd-405f-a216-fc6432d136a9.png">

**Comment by swizardlv** [comment]
@blrchen 提示500错误
![image](https://github.com/blrchen/gptlite/assets/10117682/45b805cb-1d9d-4119-ab1f-695bc4bc912f)

**Comment by blrchen** [comment]
程序近期已经更新，有几位朋友已确认能用Azure OpenAI账号成功运行。

如果仍有问题，请重新打开。
