### ISSUE TITLE
copy & paste will add extra %20 to clipboard

### ISSUE THREAD

**Issue by qliu95114** [blrchen/chatgpt-lite#18]
sometime i ask gpt to give the code. directly copy & paste is ok, but some time format need readjust in the destination editor

click copy button at the output, and paste in the target editor, i see all [SPACE] are replaced with %20 as well as other ESCAPE code. for / \ and etc. 

Hope we can fix that.

**Comment by blrchen** [comment]
The UI has been redesigned, transitioning from Ant Design to Material Tailwind. Consequently, the markdown code copy feature, which was nice to have but not essential, has not been included in the new UI. Therefore, this bug is no longer applicable.
