### ISSUE TITLE
docker-compose只添加azure链接信息报错

### ISSUE THREAD

**Issue by hiqinoon** [blrchen/chatgpt-lite#19]
您好，当我使用docker-compose部署时，配置文件仅添加了azure的相关参数。报错内容：[Error: The OpenAI API has encountered an error with a status code of 404 and message Not Found] 请问如何解决。

**Comment by hiqinoon** [comment]
这是配置文件填写的内容    
environment:
      - OPENAI_API_BASE_URL=
      - OPENAI_API_KEY=
      - AZURE_OPENAI_API_BASE_URL=https://*******.openai.azure.com/
      - AZURE_OPENAI_API_KEY=9c8***************678
      - AZURE_OPENAI_DEPLOYMENT=gpt-35-turbo

**Comment by blrchen** [comment]
@hiqinoon , 请确认一下你的AZURE_OPENAI_DEPLOYMENT是否和下图Azure门户里显示的Deployment name名字一致。初步怀疑404错误可能是因为复制了Model name，而不是Deployment name

<img width="876" alt="image" src="https://github.com/blrchen/gptlite/assets/1607381/51c1c90d-5066-4de1-840c-4fd33ef57955">

**Comment by hiqinoon** [comment]
感谢回复，问题已经解决。中间反复测试几次。有几次是重复占用key导致连接失败。感谢
