### ISSUE TITLE
suggest set edge function in route.ts when deploy on Vercel

### ISSUE THREAD

**Issue by fanweixiao** [blrchen/chatgpt-lite#52]
## Problem

Deploying to Vercel under the Hobby plan, the duration limit is capped at 10 seconds, which can be problematic as OpenAI API responses often exceed this timeframe. 

## Solution 

To circumvent the issue of receiving a 504 error, Introducing Edge Functions to route.ts by `export const runtime = 'edge';`, this helps avoid the timeout scenario.

## Ref

- Vercel functions Max Duration: https://vercel.com/docs/functions/runtimes#max-duration

**Comment by blrchen** [comment]
Hi @fanweixiao ,

Thank you for your suggestion. Would you be interested in submitting a PR if this change is tested? I'd be happy to merge it.

**Comment by fanweixiao** [comment]
@blrchen I created a PR for this, and commented on it.

**Comment by blrchen** [comment]
@fanweixiao, your PR has been merged. Thank you for your valuable contribution. I've confirmed that this change is working in both the k8s container and Vercel, I believe there's no need for an additional check to determine if the current host is Vercel.

**Comment by fanweixiao** [comment]
@blrchen great to hear that. Thanks for your work, ChatGPT Lite is well suited for small teams  👍🏻
